### ISSUE TITLE
[packages] update version pinning

### ISSUE THREAD

**Issue by osterman** [cloudposse/build-harness#133]
## what
* Upgrade to latest version for newer terraform release

## why
* we're a few releases behind and the rest of the community has updated =)
* https://sweetops.slack.com/archives/CB6GHNLG0/p1544739118674300

**Comment by solairerove** [comment]
https://github.com/cloudposse/build-harness/pull/134
@osterman review plz

**Comment by solairerove** [comment]
@osterman merged
https://github.com/cloudposse/build-harness/releases/tag/0.15.1
