### ISSUE TITLE
Missing template for README.yaml

### ISSUE THREAD

**Issue by JamesWoolfenden** [cloudposse/build-harness#137]
Love your project. But i found a really small issue. The smallest.

What?
You're missing a file  in template\README.yaml file for readme:init target to work.
If you run your target readme/init or something on a project that has no readme.yaml yet, an attempt is made to copy over this file from build.harness\templates but there is none.

**Comment by osterman** [comment]
Actually, the README.yaml is defined in each project repo. That is the data source. Then there is a templates/README.md which is a go template of our README format. 

Check out some of our other repos for examples. Nearly 99% of our projects use it.

**Comment by osterman** [comment]
Ohhhhhhh I get you. Yes, we can add a template for that.

**Comment by irl** [comment]
https://github.com/cloudposse/build-harness/blob/master/templates/README.yaml does now exist in the repository so this issue can likely be closed as fixed.
