### ISSUE TITLE
yq not installed for PPC and zLinux

### ISSUE THREAD

**Issue by cbarlock** [cloudposse/build-harness#203]
## Describe the Feature

The `helm/chart/build/package` target is dependent on yq.  Our builds run on amd64, ppc64le and s390x Linux, but on the latter two, running yq results in `cannot execute binary file: Exec format error` presumably because it is the amd64 version.

## Expected Behavior

The helm/install target should install the platform-specific version of yq.

## Alternatives Considered

Write my own target to package helm charts with no dependency on yq.  Other alternatives are to use something like `echo` to append the text that yq writes to `values.yaml`.  A more sophisticated approach would be to grep for the text and replace it if it exists (maybe using `sed`), else append it.

**Comment by Nuru** [comment]
@cbarlock I am closing this because we have no plans to support ppc64le or s390x architectures. If you have a fix that works for you, we will consider and likely accept a PR for it if it solid.
