### ISSUE TITLE
`make terraform/validate` does not to run on Terraform v0.12.X

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/build-harness#207]
## Describe the Bug
Running `make terraform/validate` on Terraform v0.12.X prints the following message: 
> Terraform 0.12 does not support validate without skipping variables

## Expected Behavior
I would expect the `terraform/validate` target to not care about this `skipping variables` flag as it doesn't seem needed, but maybe I am missing something.

## Steps to Reproduce
1. `git clone https://github.com/cloudposse/terraform-aws-ssm-parameter-store`
1. `make`
1. `make terraform/install TERRAFORM_VERSION=0.12.24`
1. `make terraform/validate`
1. Notice that Terraform validate is not run and the target prints "Terraform 0.12 does not support validate without skipping variables". 

## Environment (please complete the following information):
  - Build Harness Version: master
  - OS: MacOSX
  - Version: 10.15.4

## Additional Context
  - When I run `tf validate` locally without the Makefile / Build-harness -- I get the expected, useful output: 
```
Error: Missing required argument

The argument "region" is required, but was not set.
```
![image](https://user-images.githubusercontent.com/1392040/80243125-d5f80500-8623-11ea-9577-c5e77f110bc8.png)

**Comment by Nuru** [comment]
Terraform v0.12 support is no longer a priority. Even if it were, simply supplying `region` is not enough to get all our modules to pass, and we require that they pass before releasing them.
