### ISSUE TITLE
README.md.gotmpl should allow overwriting all areas

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/build-harness#226]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

If this repo can be used with other repositories for other organizations, both private and public, the watermarks and references to cloudposse, and all areas in general should be overwritable without having to use a custom `README.md.gotmpl`

## Expected Behavior

All parts of the `README.md` should be overwritable using only the `README.yaml`

## Use Case

Usage in a private module for a private organization

## Describe Ideal Solution

Configuration options for the yaml file that will overwrite all areas and documentation with an example yaml configuration for a private module.

## Alternatives Considered

Using a custom `README.md.gotmpl`

## Additional Context

Related https://github.com/cloudposse/build-harness/issues/223

**Comment by Nuru** [comment]
The README template in this repo is for Cloud Posse's repos. If you do not like it, you can use your own README template and point to it via `README_TEMPLATE_FILE`.
