### ISSUE TITLE
readme/init has incorrect reference to README.yaml

### ISSUE THREAD

**Issue by JRemitz** [cloudposse/build-harness#274]
To recreate:
```sh
(main) directory $ make readme/init
cp: .../directory/build-harness/templates/README.yaml: No such file or directory
README.yaml created!
```

Proposed fix:
* Remove `templates/` in path from `README_TEMPLATE_YAML` variable.

https://github.com/cloudposse/build-harness/blob/09573536cefde0c136c50b21b9ea624f7b1f84b8/modules/readme/Makefile#L5

**Comment by Nuru** [comment]
@JRemitz The `README.yaml` under `build-harness` is the source of the `README.md` for the `build-harness` repo, not a template. 

@osterman Do we want to restore a `README.yaml` template file to the `templates` directory, or are we satisfied with now having a template repo that includes the template `README.yaml`?
