### ISSUE TITLE
DEPRECATION NOTICE: git.io is shutting down (update your links!)

### ISSUE THREAD

**Issue by osterman** [cloudposse/build-harness#314]
#  GIT.IO DEPRECATION

## What 

Remove all references to `git.io/build-harness` and refer to`cloudposse.tools/build-harness` instead.

See [our Git.io deprecation documentation](https://github.com/cloudposse/build-harness/blob/master/docs/git-io-deprecation.md) for more details, including instructions on how to update.

## Why

GitHub announced that the [`git.io` redirector service is shutting down on 2022-04-29](https://github.blog/changelog/2022-04-25-git-io-deprecation/). GitHub only provided 4 days notice of this shutdown.

This means all references to `git.io/build-harness` will stop working.

## Update

GitHub amended their decision to completely shut down `git.io` (and amended the above linked [blog post](https://github.blog/changelog/2022-04-25-git-io-deprecation/))), but you should still make the change when convenient in order to preserve functionality going forward.

**Comment by Nuru** [comment]
Fixed in #315 and #317, updated in #319
