### ISSUE TITLE
Add Support for MIT, GPL3 Licenses in Readme Generator

### ISSUE THREAD

**Issue by osterman** [cloudposse/build-harness#72]
## what
* Add support for `MIT` and `GPL3` licenses

## why
* A number of our projects depend on it due to inherited licenses from other projects

**Comment by vadim-gleyf** [comment]
https://github.com/cloudposse/build-harness/pull/73

**Comment by vadim-gleyf** [comment]
Done. in [#73](https://github.com/cloudposse/build-harness/pull/73)
