### ISSUE TITLE
Update Readme Generator to use New Gomplate Inline Datasources

### ISSUE THREAD

**Issue by osterman** [cloudposse/build-harness#87]
## what
* New version gomplate of gomplate supports datasources to be defined inline

## why
* We should use this to simplify invocation

## references
- <https://github.com/hairyhenderson/gomplate/issues/349>
- https://github.com/hairyhenderson/gomplate/pull/373

**Comment by vadim-gleyf** [comment]
Depend on [Release](https://github.com/hairyhenderson/gomplate/releases) with fixed https://github.com/hairyhenderson/gomplate/issues/370
